exclude = [
    ".git/",
    ".ruff_cache/",
	"__pycache__/",
    ".vscode/",
    ".venv/",
    "dist/",
]

[lint]

# select = ["E4", "E7", "E9", "F"]
extend-select = [
	"C90", # mccabe
	"UP",  # pyupgrade
	"B",   # flake8-bugbear
	"A",   # flake8-builtins
	"C4",  # flake8-comprehensions
	"PIE", # flake8-pie
	"Q",   # flake8-quotes
	"RET", # flake8-return
	"SIM", # flake8-simplify
	"TCH", # flake8-type-checking
	"TD",  # flake8-todos
	"PL",  # pylint
	"RUF"  # ruff
]

ignore = [
	"F401", "F403", "F405",
	"E701", "E702", "E401", "E731" 
]
