version: '3.8'  

services:
  rabbitmq:
    image: rabbitmq:3.13-management
    ports:
      - "5672:5672"
      - "15672:15672"
      - "15674:15674"
    command: >
      bash -c "rabbitmq-plugins enable rabbitmq_web_stomp && rabbitmq-server"